---
- name: Install zsh
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    
    - name: Install curl
      ansible.builtin.apt:
        name: curl
        state: present

    - name: Install zsh
      ansible.builtin.apt:
        name: zsh
        state: present