---
- name: Uninstall zsh
  hosts: all
  become: true
  
  vars:
    ansible_user: jason
    home_folder: /home/jason

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: set default shell for users
      become: yes
      user:
        name: '{{ ansible_user }}'
        shell: /bin/bash

    - name: Check if {{ home_folder }}/.oh-my-zsh dir exists
      stat:
        path: "{{ home_folder }}/.oh-my-zsh"
      register: oh_my_zsh_dir

    - name: Remove {{ home_folder }}/.oh-my-zsh
      ansible.builtin.file:
        path: "{{ home_folder }}/.oh-my-zsh"
        state: absent
      when: oh_my_zsh_dir.stat.exists

    - name: Uninstall zsh
      ansible.builtin.apt:
        name: zsh
        state: absent
        
    - name: Check if /usr/local/bin/oh-my-posh exists
      stat:
        path: "/usr/local/bin/oh-my-posh"
      register: oh_my_posh

    - name: Uninstall oh-my-posh
      ansible.builtin.file:
        path: /usr/local/bin/oh-my-posh
        state: absent
      when: oh_my_posh.stat.exists

    - name: Check if /usr/local/bin/oh-my-posh exists
      stat:
        path: "/usr/local/bin/oh-my-posh"
      register: oh_my_posh

    - name: Uninstall oh-my-posh
      ansible.builtin.file:
        path: /usr/local/bin/oh-my-posh
        state: absent
      when: oh_my_posh.stat.exists

    - name: Check if {{ home_folder }}/.poshthemes exists
      stat:
        path: "{{ home_folder }}/.poshthemes"
      register: poshthemes_dir

    - name: Remove {{ home_folder }}/.poshthemes
      ansible.builtin.file:
        path: "{{ home_folder }}/.poshthemes"
        state: absent
      when: poshthemes_dir.stat.exists

